[package]
name = "led_led" # Назва вашого проєкту
version = "0.1.0" # Версія вашого проєкту
edition = "2021" # Версія Rust edition

# Додайте залежності
[dependencies]
rppal = "0.15" # Бібліотека для керування GPIO
chrono = "0.4" # Бібліотека для роботи з часом